apiVersion: v1
kind: Secret
metadata:
  name: guamanmorales-secrets
  namespace: guamanmorales
type: Opaque
stringData:
  POSTGRES_PASSWORD: "qwerty123"
  RABBITMQ_DEFAULT_PASS: "guest"
  JWT_SECRET: "cavalocal-jwt-secret-k8s"
  MAIL_APP_PASSWORD: "dummy-mail-password"
