apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guamanmorales-audit-postgres-pvc
  namespace: guamanmorales
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
